name: Run Jupyter Notebook (Tue–Sat 9AM MYT)

on:
  schedule:
    - cron: '0 1 * * 2-6'  # 1:00 AM UTC = 9:00 AM MYT, Tue-Sat
  workflow_dispatch:       # Optional: allows manual trigger

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace daily_report.ipynb

      - name: Commit updated notebook and CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_report.ipynb *.csv
          git commit -m "Update notebook and CSV output" || echo "No changes to commit"
          git push
